
# ------------------Users routes---------------------
GET http://localhost:3000/api/users/659732c919d838a15cb7bcd7

###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users/new
Content-Type: application/json

{
    "username": "User_demo",
    "firstname": "Demo first",
    "lastname": "Demo last",
    "email": "demo@gmail.com",
    "password": "0987654321",
    "avatarUrl": "/clark.jpg",
    "roles": ["User"],
    "active": true
    
}

###
PATCH http://localhost:3000/api/users/update
Content-Type: application/json

{
    "id": "659732c919d838a15cb7bcd7",
    "username": "Demo_user",
    "firstname": "Demo first",
    "lastname": "Demo last",
    "email": "demo77@gmail.com",
    "password": "0987654321",
    "avatarUrl": "/clark.jpg",
    "roles": ["User"],
    "active": true
    
}

###
DELETE http://localhost:3000/api/users/delete
Content-Type: application/json

{
    "id": "6597327619d838a15cb7bcd1"

}

# ------------------Employees routes---------------------
###
GET http://localhost:3000/api/employees/659794fe9ab447fc8050bca2

###
GET http://localhost:3000/api/employees


###
POST http://localhost:3000/api/employees/new
Content-Type: application/json

{
    "username": "Demo_user",
    "department": "IT department",
    "position": "Senior Developer",
    "skills": ["Html", "Css", "React", "Javascript"],
    "startDate": "12-29-2023"
}

###
PATCH http://localhost:3000/api/employees/update
Content-Type: application/json

{
    "id": "65979ae6224d1a66fe975c87",
    "department": "IT department",
    "position": "Senior Developer",
    "skills": ["Html", "Css", "React", "Javascript", "Python"],
    "startDate": "12-29-2023"
}

#--------------------Department routes-------------------------------
###
GET http://localhost:3000/api/departments/659794ee9ab447fc8050bc9d
###
GET http://localhost:3000/api/departments

###
POST http://localhost:3000/api/departments/create
Content-Type: application/json

{
    "name": "Del department",
    "head_of_department": "Demo_user",
    "description": "Del department was established in the year 2000"
}

###
PATCH http://localhost:3000/api/departments/update
Content-Type: application/json

{
    "id": "65979ad3224d1a66fe975c82",
    "name": "IT department",
    "head_of_department": "Demo_user",
    "description": "IT department was established in the year 2016"
}

###
DELETE http://localhost:3000/api/departments/delete
Content-Type: application/json

{
    "id": "6597a34b224d1a66fe975cad"
}