
# ------------------Users routes---------------------
GET http://localhost:3000/api/users/659aea1d3871e3fe39d1e95e

###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users/new
Content-Type: application/json

{
    "username": "User_demo2",
    "email": "demo2@gmail.com",
    "password": "0987654321",
    "avatarUrl": "/clark.jpg",
    "roles": ["User"],
    "active": true
    
}

###
PATCH http://localhost:3000/api/users/update
Content-Type: application/json

{
    "id": "659732c919d838a15cb7bcd7",
    "username": "Demo_user",
    "email": "demo77@gmail.com",
    "password": "0987654321",
    "avatarUrl": "/clark.jpg",
    "roles": ["User"],
    "active": true
    
}

###
DELETE http://localhost:3000/api/users/delete
Content-Type: application/json

{
    "id": "659cc7c4e11d8b03495921ff"

}

# ------------------Employees routes---------------------
###
GET http://localhost:3000/api/employees/659aecd9abdeeec1dd77a32d

###
GET http://localhost:3000/api/employees


###
POST http://localhost:3000/api/employees/new
Content-Type: application/json

{
    "username": "User_demo2",
    "firstname": "Demo first",
    "lastname": "Demo last",
    "department": "IT department",
    "position": "Junior Developer",
    "skills": "Html, Css, Javascript", 
    "startDate": "1-1-2016"
}

###
PATCH http://localhost:3000/api/employees/update
Content-Type: application/json

{
    "id": "659794fe9ab447fc8050bca2",
    "firstname": "Demo first",
    "lastname": "Demo last",
    "department": "Sales department",
    "position": "Sales Manager",
    "skills": [
      "Communication",
      "Accounting",
      "Time Management"
    ],
    "startDate": "12-29-2023"
}

###
DELETE http://localhost:3000/api/employees/delete
Content-Type: application/json

{
    "id": "659cc7d5e11d8b0349592204"
}

#--------------------Department routes-------------------------------
###
GET http://localhost:3000/api/departments/659794ee9ab447fc8050bc9d
###
GET http://localhost:3000/api/departments

###
POST http://localhost:3000/api/departments/create
Content-Type: application/json

{
    "name": "IT department",
    "head_of_department": "User_demo",
    "description": "IT department was established in the year 1986"
}

###
PATCH http://localhost:3000/api/departments/update
Content-Type: application/json

{
    "id": "659794ee9ab447fc8050bc9d",
    "name": "Sales department",
    "head_of_department": "User_demo",
    "description": "Sales department was established in the year 1997"
}

###
DELETE http://localhost:3000/api/departments/delete
Content-Type: application/json

{
    "id": "6599e9f3f46e36652b3da22f"
}


#--------------------Manager routes-------------------------------
###
GET http://localhost:3000/api/managers/659c4d1d9633be178a6232ce

###
GET http://localhost:3000/api/managers

###
POST http://localhost:3000/api/managers/new
Content-Type: application/json

{
    "employee": "User_demo",
    "team": ["User_demo2"],
    "projects": ["Project A"]
    
}

###
PATCH http://localhost:3000/api/managers/update
Content-Type: application/json

{
    "id": "659c4d1d9633be178a6232ce",
    "employee": "User_demo",
    "team": ["User_demo2", "User_demo"],
    "projects": ["Project C"]
    
}

###
DELETE  http://localhost:3000/api/managers/demote
Content-Type: application/json

{
    "id": "659cceb9e11d8b034959223f"
}